// Vercel Web Analytics Initialization
// This script initializes Vercel Analytics for tracking page views and events

(function() {
    'use strict';
    
    // Initialize the analytics queue
    window.va = window.va || function () { 
        (window.vaq = window.vaq || []).push(arguments); 
    };
    
    // Inject Vercel Analytics script
    // The script path will be automatically configured by Vercel when deployed
    // For local development, analytics will be in development mode
    const script = document.createElement('script');
    script.defer = true;
    
    // Determine environment
    const isDevelopment = window.location.hostname === 'localhost' || 
                         window.location.hostname === '127.0.0.1' ||
                         window.location.hostname === '';
    
    if (isDevelopment) {
        // Development mode - logs to console
        console.log('[Vercel Analytics] Running in development mode');
        window.vam = 'development';
    } else {
        // Production mode - Vercel will inject the correct script path
        // The actual script path is auto-generated by Vercel: /_vercel/insights/script.js
        script.src = '/_vercel/insights/script.js';
        script.onerror = function() {
            console.warn('[Vercel Analytics] Script failed to load. Analytics may not be enabled in Vercel dashboard.');
        };
        document.head.appendChild(script);
    }
    
    // Optional: Track custom events
    // Example: window.va('event', { name: 'custom_event', data: { key: 'value' } });
})();
